strategy:
  type: "dca"
  symbol: "BTCUSDT"
  base_order_size: 50.0        # Minimal initial size
  safety_order_size: 50.0      # Conservative averaging
  safety_orders_count: 3       # Limited number of safety orders
  price_deviation: 5.0         # Wide intervals for safety
  take_profit: 3.0             # Conservative take profit
  risk_management:
    max_drawdown: 15.0         # Strict drawdown limit
    daily_loss_limit: 5.0      # Daily loss limit
